#ifndef ERROR_CODE_DEFINES_H
#define ERROR_CODE_DEFINES_H

#define EXIT_SUCCESS 0
#define FILE_OPEN_ERROR 1
#define FILE_FORMAT_ERROR 2
#define ATOM_COUNT_ERROR 3
#define IMAGINARY_TILT_ERROR 4
#define ATOM_TYPE_ERROR 5
#define INPUT_FORMAT_ERROR 9
#define OPTION_PARSING_ERROR 10
#define AXIS_READ_ERROR 11
#define VECTOR_SIZE_ERROR 12
#define OUTPUT_SPECIFICATION_ERROR 13
#define INTERACTION_RADII_ERROR 14
#define MEMORY_EXCEEDED_ERROR 15
#define FILE_NAME_ERROR 16
#define ELEMENT_COUNT_ERROR 17
#define GRAIN_TOO_LARGE_ERROR 18

#endif // ERROR_CODE_DEFINES_H
